### ISSUE TITLE
Error Connecting to EPP Server ?

### ISSUE THREAD

**Issue by ducbo** [datahaven-net/zenaida#395]
openssl s_client -showcerts -connect registry.tld:700 -cert my-epp.pem
it's ok. 

<?xml version="1.0" encoding="UTF-8"?></epp>

perl bin/epp_gate.pl /home/zenaida/keys/epp_credentials.txt /home/zenaida/keys/rabbitmq_gate_credentials.txt

it's error.  

> Connection to registry.tld:700 failed: SSL connect attempt failed error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed at bin/epp_gate.pl line 74.

Please help me fix it

**Comment by vesellov** [comment]
Hi @ducbo ... seems you are using self-signed cert...  I remember I also had issues with that and then we just issued a normal cert and configured that on our COCCA machine.

Also I do have a positive experience with Letsencrypt certificate that we are using for our testing COCCA instance... check that file to see how to make it : https://github.com/datahaven-net/zenaida/blob/master/opt/cocca-8/make_ssl_cert

If you still want to use a self-signed SSL certificate then some additional magic probably needs to be done in the `epp_gate.pl:make_client()` method : https://github.com/datahaven-net/zenaida/blob/master/bin/epp_gate.pl#L67

but I did not went that far when I built that...

**Comment by ducbo** [comment]
Thank you. I like paypal, you can use paypal to payment.
![7DAFBEE3-504C-4D43-892B-CA39CD0EA819](https://user-images.githubusercontent.com/7487016/94049793-9a927a00-fdff-11ea-86ca-1c4e1afbffcd.png)

**Comment by vesellov** [comment]
Thanks for advice @ducbo !!!   indeed, we could add PayPal eventually :+1: 

I see it works on your phone, nice!.

Did you solved the issue and was able to run Zenaida server on your own and connect to some COCCA registry?

**Comment by ducbo** [comment]
Zenaida server working with COCCA registry. I change register,renew 2 years to 1 years for my own server. :+1:

**Comment by vesellov** [comment]
oh great! we should make that as a constant in the settings. for https://zenaida.cate.ai (our production instance of Zenaida) we always renew/register for 2 years....  probably there will be other small things that you would want to change on your own instance. if you like to change that and contribute back to the master branch - always welcome to create a pull request, @ducbo  :+1:

**Comment by ducbo** [comment]
Thank you very very much !
