### ISSUE TITLE
Create hostname, glue records, private nameserver

### ISSUE THREAD

**Issue by ducbo** [datahaven-net/zenaida#414]
I want create glue records. Eg : ns1.domainname.ai > 1.1.1.1
ns2.domainname.ai  > 2.2.2.2

Please update. Thank !

**Comment by vesellov** [comment]
Hi @ducbo !  Thanks for your request. We are currently not supporting that. For our .AI zone which we are mainly building Zenaida for we never received such a request from our customers... 

As I understood the glue records principle - it only makes sense when domain wants to use nameservers from the same DNS zone which is used by the domain, right? 

https://en.wikipedia.org/wiki/Domain_Name_System#Circular_dependencies_and_glue_records
